---
After:
  - framework/*
  - cms/*
---
StaticExporter:
  extensions:
    - DocumentationStaticPublisherExtension
  disable_sitetree_export: true
Controller:
  extensions:
    - ControllerExtension
QuickFeedbackExtension:
  redirect_field: true
  rate_limit: 1