--- 
format: 1
handler: 
  commit: a12169c9e0fd1fd65ccdb2e6f404be590e5920de
  branch: master
lock: false
repository_class: Piston::Git::Repository
repository_url: git@github.com:silverstripe/silverstripe-sapphiredocs.git
