--- 
format: 1
handler: 
  commit: b1c93bd27a232267a2ab9e05f9372982b0781236
  branch: master
lock: false
repository_class: Piston::Git::Repository
repository_url: git://github.com/silverstripe/silverstripe-sapphiredocs.git
